### ISSUE TITLE
HTML og CSS til webbrowser

### ISSUE THREAD

**Issue by keit0017** [keit0017/VCDIO3#2]
Det skal være muligt at oprette brugere, hente brugere og opdatere brugere fra hjemmesiden. Lav en hurti hurti og flot hjemmeside der elegant viser de ovenstående ting.

**Comment by Joe-Briefcase** [comment]
Sørg for at brug gode id'er til HTML elementerne og brug kommentarer i CSS stylesheet så man kan se hvad der hører til hvad.

**Comment by TristanEmilStenalt** [comment]
Umiddelbart udseende(HTML & CSS) lavet, men er der en elegant måde at vise flere roller på? lige nu er der kun et felt til én rolle i tabellen...

**Comment by Joe-Briefcase** [comment]
Ja, kan godt se det ville være svært at få plads til flere roller på én række. Man kunne evt. lave noget med en dropdown der vises når man hover over antal roller?

https://www.w3schools.com/css/css_dropdowns.asp
